### PR TITLE
Fix npm audit issues, updated all dependencies and fix lint

### PR DESCRIPTION
**Pull request by Igor-Lopes**
## Fixes
* NPM audit reported issues
* Update all dependencies
* Fix lint issues

### CODE REVIEW

**Comment by wesleytodd** [comment]
Hey @Igor-Lopes, thanks for the report.  Can you outline the issues you are reporting?  Also, if you want to update dependencies can you submit one PR for each dep?  

Lastly, the lint issues are interesting.  Is that because you updated `standard`?  If you want this to be merged it will for sure have to be separate PR's for each issue.  Thanks!

**Comment by Igor-Lopes** [comment]
Hi @wesleytodd , the lint issues were due to standard update. The most important updates are the ones reported by `npm audit`. I've made all changes to make sure the tests are passing after all updates, however I understand your concern regarding these changes and the need of separated PR's.

**Comment by wesleytodd** [comment]
Can you make sure to post the output from `npm audit` which you are seeing?

**Comment by Igor-Lopes** [comment]
@wesleytodd  Do you want me to open a PR for all `npm audit` issues, or should I open separate PR's for each dependencie reported on `npm audit` as well ?

**Comment by wesleytodd** [comment]
I think one pr with all the audit output and updates if fine.  I guess I am just surprised that there are any to fix since I install this package regularly and have not seen any (other than the recent non-issue published in the recent minor release (https://github.com/tj/node-migrate/commit/fd16f79367d910fa72ea0a749c3469dbe3610e77).

**Comment by Igor-Lopes** [comment]
Here's the `npm audit` report I'm getting:

```
 === npm audit security report ===                        
                                                                                
# Run  npm install --save-dev mocha@5.2.0  to resolve 2 vulnerabilities
SEMVER WARNING: Recommended action is a potentially breaking change
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ debug                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ mocha [dev]                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ mocha > debug                                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/534                       │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Critical      │ Command Injection                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ growl                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ mocha [dev]                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ mocha > growl                                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/146                       │
└───────────────┴──────────────────────────────────────────────────────────────┘


# Run  npm install --save-dev standard@12.0.1  to resolve 4 vulnerabilities
SEMVER WARNING: Recommended action is a potentially breaking change
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ debug                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ standard [dev]                                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ standard > eslint > debug                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/534                       │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ debug                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ standard [dev]                                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ standard > eslint-plugin-import > debug                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/534                       │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ debug                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ standard [dev]                                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ standard > eslint-plugin-import >                            │
│               │ eslint-import-resolver-node > debug                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/534                       │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ debug                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ standard [dev]                                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ standard > eslint-plugin-import > eslint-module-utils >      │
│               │ debug                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/534                       │
└───────────────┴──────────────────────────────────────────────────────────────┘


found 6 vulnerabilities (5 low, 1 critical) in 586 scanned packages
  6 vulnerabilities require semver-major dependency updates.
```

**Comment by Igor-Lopes** [comment]
I forgot to mention that the `npm audit` report is related do dev dependencies only, so when you actually install it on your project, npm doesn't give any warnings:

```
npm install --save migrate
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN node_app@1.0.0 No description
npm WARN node_app@1.0.0 No repository field.

+ migrate@1.6.2
added 20 packages from 13 contributors and audited 21 packages in 5.639s
found 0 vulnerabilities

```

**Comment by Igor-Lopes** [comment]
And here's the list of outdated dependencies:

```
Package     Current  Wanted  Latest  Location
chalk         1.1.3   1.1.3   2.4.1  migrate
commander    2.16.0  2.19.0  2.19.0  migrate
dateformat    2.2.0   2.2.0   3.0.3  migrate
dotenv        4.0.0   4.0.0   6.1.0  migrate
mocha         3.5.3   3.5.3   5.2.0  migrate
standard     10.0.3  10.0.3  12.0.1  migrate

```

**Comment by wesleytodd** [comment]
Ok, so neither of these are security voulns with this package.  Both of those are dev dependencies (and why mocha installs `growl` is just silly), but I am up for updating them as long as each one, and related changes, are separate PRs.

**Comment by wesleytodd** [comment]
Commenting at the same time :)

**Pull request closed without merging**
