### PR TITLE
refactor: modernize code using es6 classes

### PR DESCRIPTION
**Pull request by danielpza**
Modernize code by replacing function constructors with modern [ES6 classes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes)

See https://github.com/tj/node-migrate/pull/206/files?diff=unified&w=1 for a better diff of the PR

### CODE REVIEW

**Comment by wesleytodd** [comment]
I am not a big fan of "modernize" PRs for the sake of "modernization". Do you have more concrete reasons to prefer this?

I am not against it, and I would never write new code with the old style, it is just "change for changes sake" is rarely a good thing.

**Comment by danielpza** [comment]
> I am not a big fan of "modernize" PRs for the sake of "modernization". Do you have more concrete reasons to prefer this?

No concrete reason, it would make it easier to maintain if we use a more familiar code (in this case classes instead of the obscure function prototypes).

**Comment by wesleytodd** [comment]
I generally agree with that sentiment. [I started a whole rewrite](https://github.com/migratejs) I intended to release as the next major in fact, just never had time to circle back on it.  So I am just not sure if this kind of change in such a slow paced project is worth it. I dont want to decline a good and well meaning contribution though.

**Comment by danielpza** [comment]
Closing to keep inbox clean. Lmk if you change your mind.

Cheers

**Pull request closed without merging**
