### PR TITLE
Coffeescript support

### PR DESCRIPTION
**Pull request by boz**
Copied from #31, which has some other changes.

### CODE REVIEW

**Comment by gustavnikolaj** [comment]
It would be nice if the coffeescript support was hidden behind a flag, so that all non-coffee script uses did not need to load unnecessary stuff.

**Comment by sungwoncho** [comment]
Any news?

**Comment by LinusU** [comment]
I think that this should work exactly as it works in mocha, that way we can support other transpilers as well.

**Comment by wesleytodd** [comment]
This should be working in the `1.x` branch with the `--compiler` flag.  @boz, let me know what you think over there, and close this if you are satisfied.  Thanks!

**Comment by boz** [comment]
Hey @wesleytodd happy to see the progress!  I've been out of the node game for some time now; I'll take your word for it.

Cheers

**Pull request closed without merging**
