### PR TITLE
fixed typo extention -> extension

### PR DESCRIPTION
**Pull request by jmjpro**

### CODE REVIEW

**Comment by LinusU** [comment]
Thanks 👍

**Comment by wesleytodd** [comment]
Oh wow, at least I was very consistent in my miss-spelling :)

Probably because I auto-completed them all from my first typo.  @LinusU did you publish this?  Because unfortunately if we do not add an alias to the broken spelling, this is a major version bump.

**Comment by jmjpro** [comment]
I can create another pull request that 1) automatically creates the
migration using the template extension and 2) restore extention to the
external API and then convert it immediately to extension so as not to
require a major version jump.

**Comment by wesleytodd** [comment]
Can you make 2 separate PR's?  I just dont want to block releasing this if we have to go back and forth on the auto-~~"extention"~~"extension" ;) thing.  

For the restore the existing api thing, to make sure we are on the same page, it should accept both flags, and log a deprecation warning if the incorrect version is used.  Then we can remove it when we go to the next major version.

**Comment by LinusU** [comment]
> did you publish this? Because unfortunately if we do not add an alias to the broken spelling, this is a major version bump.

Hehe, maybe I was a bit happy with the merge button 😅 

Maybe an easy fix is:

```js
const index = process.argv.indexOf('--extention')
if (index !== -1) process.argv[index] = '--extension'
```

**Comment by wesleytodd** [comment]
I would prefer we don't modify `argv`, but the general idea is what I was thinking as well.  Maybe a bit more like:

```
if (program.extention) {
  console.error('deprecated...')
  program.extension = program.extention
}
```

**Pull request merged**
