### PR TITLE
Added example for using a custom state storage

### LINKED ISSUE #127: Custom state storage should be documented better
The README says,

>> As long as what goes in as `set` comes out the same on `load`, then you are good to go!

It should say something about what `set` actually looks like, because its shape says something about how users can persist it. Is it a string? Is it something the user can call `JSON.stringify` on, and restore with `JSON.parse`?

Reading the source, it looks like `set` is a `MigrationSet` object, and the `MigrationSet` has the `store` as a property. Should `load` return a `MigrationSet` object with a `store` as a property, then? It doesn't look like the `FileStore` default does anything like that, so I guess it's fine not to?

Also, some guidance should be provided about what `load` should return when no migrations have been run. Presumably `store` hasn't been run at all yet (unless it's called on `init`?) Is `null` ok? Should it be an empty object?

Reading the source, it looks like "An empty object should be a safe bet for an initial state, and serialising/deserialising `set` with `JSON.stringify`/`parse` should be ok`.

### PR DESCRIPTION
**Pull request by roemba**
Resolves #127

### CODE REVIEW

**Comment by wesleytodd** [comment]
A few comments:

1. Because the `migrations` table is not created, won't this just error every time?  Maybe the save should do a `CREATE IF NOT EXISTS`?
2. Can you put this in a directory with a descriptive name like the other examples?
3. Do we care that the examples are not runnable in all currently supported versions of node?  This use of static class properties will not work in node 6, which is still in it's support window.

**Comment by roemba** [comment]
Good comments, integrated both 1 and 2.

For 3, I found out that `static` _is_ supported since Node 4 ([source](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/static#Browser_compatibility)) but `async` is not ([source](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function#Browser_compatibility)), so I've rewritten the example to use promises.

**Comment by wesleytodd** [comment]
3. I am not sure this is correct.  I usually use node.green for this, and here it says it errors in node for. https://node.green/#ES2015-functions-class-static-methods

You can test with docker pretty simply:

```
docker pull node:4 && docker run -it --rm -v "$PWD":/usr/src/app -w /usr/src/app node:4 node custom-state-storage.js
```

If it is working the file should run no problem.

**Comment by roemba** [comment]
Isn't 4 already out of support? https://github.com/nodejs/Release#release-schedule 
If you mean 6, than the website you linked shows that static methods are supported by version 6.
Any case, if this still concerns you I am happy to remove it, is is only small change after all.

**Comment by wesleytodd** [comment]
Oh, wow sorry I did mean 6.  I originally commented about 6 but then switched to 4 in my next comment.  Yeah, if it works in 6 I am good with it!

**Comment by wesleytodd** [comment]
Sorry to keep circling back on this.  But it might be better to show storing it in a `jsonb` field, as opposed to having to serialize it to a string yourself.  Also, you could avoid the `delete from` and just do a single `update`.

**Comment by roemba** [comment]
I made the requested changes, and also tested these with a local Postgresql database. Is indeed much cleaner without the JSON.stringify and JSON.parse

**Comment by wesleytodd** [comment]
Awesome @roemba!  I will take a look at this soon and get it merged!

**Comment by wesleytodd** [comment]
Merged (squashed and small changes) in 067797c.

**Pull request closed without merging**
