### PR TITLE
Improve custom-module load and extend compiler support for multiple extensions

### PR DESCRIPTION
**Pull request by dario1985**
- use same common require-fallback strategy to load user custom-modules (eg. Store and Compiler) 
- extend compiler multiple extensions support eg. `--compiler "js,js6,ts:@babel/register`

### CODE REVIEW

**Comment by wesleytodd** [comment]
Hey @dario1985, thanks for the PR!  I think there are a bunch of good parts here, but we cannot accept this as one PR.  Can you break the two new features out into separate PR's and just remove the version bump change?

**Comment by dario1985** [comment]
hey @wesleytodd, I removed the bump change and splitted it in 2 commits (as one depends of the other).

What is the release schedule? As I saw some old changes that are still not released on the npm registry.

**Comment by wesleytodd** [comment]
Thanks!  I was hoping to have a conversation about the changes independently, but it's not a big deal to have them both here I guess (unless we decide not to take both).

1. Common require strategy: The only thing missing from this is a test to cover the new feature.  Can you add that?  If we have it we can merge that as is I think.
2. Multiple compilers: My question about this one is, are there other examples of this type of handling?  Can you reference them so I know that users of compilers will understand and feel comfortable with them?

There is no "release schedule".  We release as we have code which warrants it.  Once we get these questions sorted out we will probably do one right away.

**Comment by wesleytodd** [comment]
@dario1985 If we are going to move forward with this, I will need those questions above answered.  If we can get it together in the next week it can go out with the other stuff I plan on releasing.  Please let me know if you want to continue working on this feature.

**Pull request closed without merging**
