### PR TITLE
Small typo fix

### PR DESCRIPTION
**Pull request by tmikeschu**
Hello! Noticed this while setting up a new project.

### CODE REVIEW

**Comment by wesleytodd** [comment]
Hey! Thanks for the PR.  That was copied from the output of the [actual help text](https://github.com/tj/node-migrate/blob/master/bin/migrate#L13), want to fix it there as well?

**Comment by tmikeschu** [comment]
Good catch, thanks @wesleytodd !

**Comment by wesleytodd** [comment]
Just an operational note, I have been trying to squash merge when folks have a single PR with multiple commits.  My end goal here is to setup conventional commit and auto deploy actions, so it will be important in that case that the merge commit on PRs is clean and follows the format.

Since I have not been able to work on this library for a bit (and have a next major in progress), I have also not documented this.  Also, it probably doesn't matter lol.  But just wanted to post it in case you cared @LinusU :P

**Comment by LinusU** [comment]
Nice, yeah that would have been better, will try and remember next time! 👍

**Pull request merged**
