### PR TITLE
fix(lib/migrate): do not pass error to callback on successful promise

### LINKED ISSUE #133: Promise resolving to truthy is treated as rejection
https://github.com/tj/node-migrate/blob/93dfb65e3605e7f2b4298db7e06523a5ee2438aa/lib/migrate.js#L47-L51

Be careful when mixing promises and callbacks. This passes a node-style callback as a `.then()` handler to a promise, meaning that the resolved value of the promise is the first argument of the callback, indicating to the callback that there was an error if the resolved value of the promise is truthy.

This should probably read `.then(() => completeMigration(null))` since `completeMigration()` only cares about whether it was passed an `err` argument.

### PR DESCRIPTION
**Pull request by gpinhey**
closes #133

### CODE REVIEW

**Comment by wesleytodd** [comment]
Could you also add a regression test for this?  Preferably also keep the PR to the single commit.  You can see similar regression tests:

https://github.com/tj/node-migrate/blob/master/test/issue-33.js
https://github.com/tj/node-migrate/blob/master/test/issue-92.js

I can merge it up after that!  Thanks for the good work!

**Comment by gpinhey** [comment]
Tests have been added. I re-used the existing suite for testing promises.

**Comment by gpinhey** [comment]
Quite welcome, thanks for responding.

Next step: updating the readme to mention promises are an option 😉

**Comment by gpinhey** [comment]
Just checking in as it's been a couple weeks, was there anything else you needed on this?

**Comment by wesleytodd** [comment]
Oh sorry, busy with life and forgot.  I will do this today, thanks for following up!

**Comment by wesleytodd** [comment]
Published as `1.6.1`.  Thanks!

**Comment by gpinhey** [comment]
I think you might have merged an earlier commit somehow, the regression test isn't on `master`.

**Comment by wesleytodd** [comment]
Oh, interesting.  I did notice that I already had a branch named after this.  I must have missed the pull.  I will fix that right now.

**Comment by wesleytodd** [comment]
Ok, the updated commit is there.   I didn't re-release since it was just the tests which were missing.

**Pull request closed without merging**
