### PR TITLE
Add support for configuration via 'rc'

### PR DESCRIPTION
**Pull request by zebulonj**
This uses the `rc` module to add support for all (with one exception noted below) command-line options on all migrate commands. Via `rc`, this supports various configuration locations and formats (https://www.npmjs.com/package/rc#standards).

(Exception: I didn't connect `rc` to the `--chdir` option. It didn't seem right.)

Noteworthy:
- There is some redundancy here, as `rc` and `commander` both handle command-line arguments. The approach I've taken starts with `rc`, casting a wide net for configuration, then hands off to `commander` in the form of "default" values. In turn `commander` will pick up additional command-line options in the short form (e.g., `-s` vs. `--store`).

- Some of the configuration formats supported by `rc` will not be available in practice, because of incompatibility with `migrate` option naming. For example, due to the hyphen, `--template-dir` cannot be set via environment variables otherwise parsed by `rc`.

See tj/node-migrate#101 for background.

### CODE REVIEW

**Comment by zebulonj** [comment]
Note: I'll add documentation and tests if there's general buy-in to this approach.

**Comment by zebulonj** [comment]
On second thought, I'm going to connect `rc` to the `--chdir` option. I already see a use-case. Commit to follow...

**Comment by LinusU** [comment]
Wrote some thoughts on using `rc` here: https://github.com/tj/node-migrate/issues/101#issuecomment-362548594

**Comment by wesleytodd** [comment]
Lets make sure we have consensus in #101 before merging this, but if we like it, can you add at least one test and squash these to one commit?

**Comment by wesleytodd** [comment]
Hey, it has been a while on this, but I was wondering if https://github.com/tj/node-migrate/pull/88 solved this same request?

**Comment by zebulonj** [comment]
I’m going to take a closer look, to confirm, this week. Thanks.

**Comment by zebulonj** [comment]
As best I read the changes in #88, it doesn't allow you to replace command-line options (e.g., `--migrations-dir`, `--store`,...) with a `.env` file. It looks like it just processes the `.env` file and sets the corresponding variables on `process.env`. As I recall (and a quick look doesn't reveal differently), the code doesn't look to the environment to set the migration directory, store, template generator, or other machinery of the module.

If that this assessment is accurate, then #88 does not solve this same request. The principal goal of this request is to save developers the need to remember and include `--migration-dir <X> --store <Y>` when executing commands (e.g., `migrate up`) in the course of development.

**Comment by wesleytodd** [comment]
Yep you are absolutely correct.  I forgot that this PR was intended to add that type of configuration.  Let me think on this and get back to you again, sorry for the back and forth.

**Comment by zebulonj** [comment]
@wesleytodd No worries. I let this PR sit because it seemed like you weren't sure which direction you wanted to go. We are using a fork with this PR merged in production, but I'd love to shift back to the maintained fork. If you want some changes to this PR, or if you want it re-implemented/updated to reflect the project's evolution, just give me some direction and I'll get it done.

**Comment by wesleytodd** [comment]
For sure @zebulonj, I want to get this going but need to make sure it is the best direction.  I am thinking about it now as I have since run into the use case this helps solve.  I will update here with my thoughts once I have the time to write them all down.

**Comment by zebulonj** [comment]
@wesleytodd Where do you stand on this?

**Comment by wesleytodd** [comment]
Sorry, I have been a bit busy (recently had a baby 👼) and haven't had time to follow up on this.  But to start the conversation, my thought is that this is best done with environment variables, which then means we can just piggyback off of the `.env` file support.  If we just define all of the flag defaults with something like the following we can avoid adding a new dependency:

```javascript
.option('-g, --generator <name>', 'A template generator function', process.env.MIGRATE_GENERATOR || path.join(__dirname, '..', 'lib', 'template-generator'))
```

Anyway, that is my quick idea, what do you think?

**Comment by zebulonj** [comment]
My initial thought is... congrats on the baby. My "baby" boy turns five next month.

Regarding use of `.env` files, I have some initial reservations... in that many if not most of the projects I've worked in `.gitignore` the `.env` files because they contain secrets, but we explicitly want the migration configuration to follow the code-base so someone can quickly install and `migrate up`. Copying things into a `.env` file that serves multiple purposes is just one more thing between a developer and writing code.

Can you explain your resistance to the `rc` file? It's hard for me to see it as controversial, when it's so common. Good enough for Babel, why not good enough for other tools that exist in the same functional space? You say "one more dependency," but is that so bad?

**Comment by wesleytodd** [comment]
My reluctance to add `rc` is because of a few things:

1. If we can avoid having users muddy up their projects or home directories with more dot files, I would prefer it.
2. As far as dependencies go, this is a complicated one.  It has a bunch of semantics which users of `migrate` would need to learn.
3. This would make debugging issues much more difficult, because the cause could be in any of the places `rc` checks for configuration.  Including "global" configurations, which I always try to avoid.

Note: I realize this is a change from my earlier opinions from the other issues.  I have thought about this problem a bunch and tried a few different ways of solving it in my projects to figure out what I think is the best way forward.  Also, these are problems I have seen with other tools, like `babel`, who use this approach, so it's popularity holds little weight with me.  I want to get it right before we do anything since all you have to do now is wrap it with your own script which sets your defaults, so it does not make anything impossible.

I will comment more on the `.env` idea later, but I think your point is good.  So let me think about it more.

**Comment by zebulonj** [comment]
You know... I find the "you can wrap it with your own script" compelling. Hadn't really thought about that much, but a light wrapper might fully address my needs.

**Comment by wesleytodd** [comment]
Composition is a powerful paradigm :)

This is often why I am hesitant to make one all powerful module with all the bells and whistles.  With a module ecosystem like npm around it is simple enough to just wrap a new module.  

FWIW, I have not pushed yet, but I am doing this in one project with the module `@wesleytodd/migrate-pg`, which is a wrapper around my common settings with `migrate` and `pg` and a few bells and whistles.  It has been working well for me so far, but does make it clear this module could have a better javascript api.

**Comment by zebulonj** [comment]
Circling back to this... it's served me very well to write a thin wrapper around `node-migrate` to handle my project-specific configuration and needs.

**To others evaluating various migration layers for your Node projects**, I'd say this: The three characteristics of `node-migrate` that have made it a hands-down winner in my book are:
 - the fact that it is entirely un-opinionated about the underlying migration target (I use it to migrate both MySQL databases and ElasticSearch mapping configurations, and can interact with those targets in migrations the same way I do in application code),
 - the clean and transparent way that it exposes a programmatic API, allowing users to wrap it easily to add features or to integrate it directly into applications and deploy tooling,
- the extensibility and flexibility that comes with the ability to define your own migration store.

Thanks, @wesleytodd. 👏

**Pull request closed without merging**
