### PR TITLE
Use slugify instead of slug

### PR DESCRIPTION
**Pull request by davedoesdev**
Because of https://github.com/dodo/node-slug/issues/82

slugify was fixed in https://github.com/simov/slugify/commit/e8f8a694c0839c77e53e336616b1e6e3b1c7feab

### CODE REVIEW

**Comment by wesleytodd** [comment]
While I am not opposed to this change, in an effort to reduce any churn it might cause, can you make a case for why this matters?

The use case for this module does not care at all for a redos because it is a cli tool.  I made my [very simple case for this here](https://github.com/tj/node-migrate/pull/77#issuecomment-335911777), and am not sure anything has changed.

**Comment by davedoesdev** [comment]
Nothing, apart from github's security spam. Feel free to close.

**Comment by wesleytodd** [comment]
Ok, will close. I brought this up to the people who matter, apparently something is coming soon to help with this kind of spam.

https://twitter.com/wesleytodd/status/1026253123449311232

**Comment by davedoesdev** [comment]
That would be great, it would help all the way up the dependency chain.
Currently when I get a security alert, I step down the chain to the last responsive project.
Maybe that isn't a common response.

**Comment by wesleytodd** [comment]
Yeah, I think the it is a good response, even if it is not common.  I do the same thing usually.  

The problem is that the tooling is very broad in its messaging because it cannot tell if you are using the package in a vulnerable way, especially if it is deep in the dep tree.  Hopefully in the future the tool maintainers can help here.

**Comment by wesleytodd** [comment]
To follow up, I just published `v1.6.2` with the patched version of `node-slug`.

Fixed here: https://github.com/dodo/node-slug/issues/82

**Pull request closed without merging**
