### PR TITLE
Closes issue #92

### PR DESCRIPTION
**Pull request by sms-system**

### CODE REVIEW

**Comment by wesleytodd** [comment]
I assume this is related to the new feature from #91.  My only comment:

Can you remove the nested ternary and turn it into more legible `if`'s?  Once that is done I can merge and publish this.

**Comment by wesleytodd** [comment]
Actually, can you also add a regression test for this issue?

**Comment by sms-system** [comment]
Added tests that cover the problem

**Comment by wesleytodd** [comment]
Published as `1.1.1`

**Pull request closed without merging**
