### PR TITLE
allow using esm modules in migrations 

### PR DESCRIPTION
**Pull request by Ti-webdev**
The first commit add support migrations with .ejs extension
But without upgrade dependencies (second commit) dynamical import for that does not supported with old version of standard (standard Parsing error: Unexpected token import).
So time to update everything...

### CODE REVIEW

**Comment by mkovel** [comment]
@Ti-webdev 
any updates here?

**Comment by mkovel** [comment]
@wesleytodd Can you merge it?

**Comment by mkovel** [comment]
@Ti-webdev  Could you also add info to Read.me according to your imps?

**Comment by wesleytodd** [comment]
Sorry, I did not see this PR until now, but also no we cannot merge it.  This makes sweeping changes to the code base.  I will happily review and take small updates, especially if there is a small PR which only does what the title suggests this would do.  @Ti-webdev, if you are interested in slimming this one down to a tight scope to enable ESM usage that would be great.

@mkovel, many folks follow this repo, so please be courteous folks time and energy and consolidate your posts together to reduce noise in the future. Thanks!

**Comment by wesleytodd** [comment]
Addressed in #199

**Pull request closed without merging**
