### PR TITLE
Issue #148: Allow absolute path for migrations dir

### PR DESCRIPTION
**Pull request by akivajgordon**
Closes issue #148

- Wrote the failing test first
- made the fix
- re-ran the tests, all passed.

### CODE REVIEW

**Comment by wesleytodd** [comment]
Good call.  Only one nit pick, can you add a test in your new file for the relative behavior as well?  That way we ensure we don't break either way moving forward.  If you add that I will prepare a release for this soon, probably along with a few other things I have been planning on releasing in the next minor release.

**Comment by akivajgordon** [comment]
@wesleytodd Done! Let me know if you have any other recommendations.

**Comment by wesleytodd** [comment]
Awesome, I will take a look at this tomorrow.  Thanks for the contribution!

**Comment by akivajgordon** [comment]
@wesleytodd Just checking in on this... anything I can do to help move this forward?

**Comment by wesleytodd** [comment]
Hey, I am so sorry that I dropped the ball on this.  I was out for a bit having a child and I guess github cannot handle all the notifications, because it did not show me this one until now.  I will take a look this weekend and we should be good to release!  Again, sorry about the delay!

**Comment by akivajgordon** [comment]
@wesleytodd No problem at all – congrats on your child! Wishing you all the best with that!

Thanks for merging.

**Comment by Jaskar14** [comment]
@wesleytodd Hey, is this option anywhere in the documentation? It was difficult to find without looking at issues/source code. If it isn't in the documentation, I can make a pr, but wanted to double check with you first

**Comment by wesleytodd** [comment]
PR is very welcome!  Docs are all in the `README.md`.

**Pull request closed without merging**
