### PR TITLE
CLI Supports Mixins with `--use` flag

### PR DESCRIPTION
**Pull request by gobengo**
Make the CLI extensible via a `--use path/to/mixin.js` flag and mixin modules. Mixins are functions that will be passed `require('migrate')` before `require('migrate').set.migrate()` is invoked. Use this to alter the behavior of the migration Set.

This adds a point of extensibility to allow projects to customize the behavior of migrate without having to create their own cli script.

I created an initial mixin, [node-migrate-mongodb-persistence](https://github.com/gobengo/node-migrate-mongodb-persistence), that resolves issue #29, at least for others using MongoDB. There's no reason a similar mixin library couldn't be made for other storage engines.

Thoughts?

### CODE REVIEW

**Comment by jamessidhu** [comment]
It would be really good to see this merged finally +1.

**Comment by jc888** [comment]
+1

**Comment by crowleym** [comment]
+1
Is there a reason why this has not been merged yet?

**Comment by LinusU** [comment]
I think that this is a **very ugly** way to solve this problem. If we would merge this we can never again change any *internal* api without the possibility breaking third party modules. Very bad.

A better approach would be to specify an api of which to follow when storing state, very similar to what [express is doing with sessions](https://github.com/expressjs/session#session-store-implementation).

**Comment by gobengo** [comment]
@LinusU I agree that it would be ideal for there to be a more stable (ie defined) interface for the object that mixins would act on.

To be fair, there is sort of an implicit API for storing migration sets: 'save' and 'load' methods like the ones you see [in the sample mixin](https://github.com/gobengo/node-migrate-mongodb-persistence/blob/master/index.js#L32) I made.

It's a little awkward and ambiguous, though, what those methods should do. iirc they have to throw certain events when they're done, which is odd. An errback or returning a promise may be more specific.

**Comment by LinusU** [comment]
Having an implicit api is exactly the kind of thing that I was expressing my feelings against. There is a number of problems with the state saving as it is now and I'm not sure that a simple `load`,`save` api would solve this in a good way. I think that the store api needs to be informed on what is happening instead of being informed on the final state.

I will try to do a proper writeup on all the problems that we currently have, and then propose how we should solve them, in a new issue as soon as possible.

**Comment by aneilbaboo** [comment]
Has there been any progress on this issue?

**Comment by ncoden** [comment]
Poke @tj

**Comment by wesleytodd** [comment]
Hey, this is really old, but I think there is merit in the idea, but I think a different approach is better.  Instead of providing api inside this module, I think it would be better to expose more functionality on the javascript api making it easier to to wrap this module with custom interfaces.  I might spend some time on this idea soon if anyone has opinions on how it is done before I start.

**Comment by ggirodda** [comment]
it would be really nice to have the possibility to overload the functions of the migrate module. In my case I have to start a process before the call to `load` function, and kill it after, but for now the only way to achieve that is to clone the bin files that use the load function and put the logic inside

**Pull request closed without merging**
