### PR TITLE
allow already-called register

### PR DESCRIPTION
**Pull request by flisky**
`ts-node/register` doesn't work for me.

BTW, is there any other ways to support typescript? Thanks!

### CODE REVIEW

**Comment by wesleytodd** [comment]
Hey @flisky.  I am not familiar with `ts-node`, or what specifically you are reporting.  Can you show the output and the command which resulted in this error?  Based on the changes, it looks like the compiler you are trying to register is not exporting a function.  Which is the interface this module supports.  Again, maybe I am miss-understanding your issue, so more context would help.

**Comment by flisky** [comment]
I'm sorry it's unclear, and yes, the problem is exactly as you said.

the `ts-node/register` is a simply call on `require("ts-node").register()`.

And also, I need call muilty registers, but currunt `compiler` option doesnot suppot repeatable values. With the patch, I can do anything as I like.

It's just like 'require' option for `nodejs`. Maybe I only need a way to pass the option to nodejs directly? Thanks again.

**Comment by wesleytodd** [comment]
This change would silently fail when the compiler is not valid according to what we support.  And if it is valid, then this change is no different than the current behavior.  So I think we can break this down into two parts:

1. The `ts-node/register` method. Which needs to be wrapped to support the common format. Could probably be as simple as `module.exports = require("ts-node").register`.
2. Supporting multiple `compilers`.  This is not something which has been brought up before.  Maybe you can talk more about why you need this feature, and why the other existing ways do not solve your sue case.  That would help me make sure we are correctly helping to get what you need.

Thanks!

**Comment by flisky** [comment]
I need to call the following registers:

```
require("ts-node/register");
require("tsconfig-paths/register");
require("source-map-support/register");
```

Re 1: Yes, absolute. But it's a little cumbersome to me.

Re 2: It can be fixed as the some way like 1.

I rethink, and use `NODE_OPTIONS='--require ./registers'` instead of '--compiler' option.

Please feel free to close this.

**Comment by LinusU** [comment]
I think that we should make an effort to align ourselves with other similar tools. I think `mocha` is a good example to look at, they recently refactored their support and dropped `--compiler` in favour of `--require`.

Here are some more info on that change: https://github.com/mochajs/mocha/wiki/compilers-deprecation

It seems like there is a consensus of having a `register.js` file that will automatically register support among almost all tools (e.g. `ts-node`, `source-map-support`, `coffee-script`, `babel-core`, ...)

**Comment by wesleytodd** [comment]
Interesting, this has changed then.  Because it used to be standard to call it with options AFAIK.  How do you pass the `extensions` options, like if you want to call your files `.js` even if they have jsx in them?

**Comment by LinusU** [comment]
I think you need to create your own file then, e.g.

`register.js`

```js
require('ts-node').register({ ... })
```

```sh
mocha --require ./register ...
```

**Comment by wesleytodd** [comment]
Ugh, well that is a regression of usability IMO.  Ok, well I would like to read through atleast the most popular ones to make sure we are doing the right thing, but I am pretty sure it is not what is currently in the PR.  I will keep it open for tracking, and if @flisky wants to do the final PR (or anyone else) which gets us all what we need then great, otherwise I can try to take a look this week.

**Comment by LinusU** [comment]
Yeah, I don't think that what's in the PR is what we should do

> Ugh, well that is a regression of usability IMO

I thought the same thing when reading the mocha changelog, but I haven't really had a case where I need to pass any options yet 😄

**Comment by flisky** [comment]
Thanks, @LinusU. That's a step further I think.

I'm very glad if you can take it over, @wesleytodd.

**Pull request closed without merging**
