### PR TITLE
replace --compiler to --require

### PR DESCRIPTION
**Pull request by hudovisk**
I Found #105 while trying to use node-migrate with typescript and tried to solve it. 

This should conform to the more standard way of registering compilers, based on mocha.

### CODE REVIEW

**Comment by wesleytodd** [comment]
Hey @hudovisk, this looks like a good start.  What I would like to see is the following:

- Backward compatibility:  Support both flags, and use `depd` to deprecate usage of the `--compiler` flag (but keep its behavior)
- Documentation: How do you use it?  The old flag supported telling it what file types, how do you do this with the new flag?
- Nit pick: pull your shared `collect` function into the `lib` directory

The goal would be to add this and do a major release (the breaking change being the deprecation warning, but let me look and see if there are other things we can prepare for that release).  Then we can tee up another major release for when we remove the old flag.  Sound good?

**Comment by hudovisk** [comment]
@wesleytodd sounds great, can you check again? If you think everything is ok I can move on to the documentation. I use it this way `--require ts-node/register`. I think we can use  https://github.com/mochajs/mocha/wiki/compilers-deprecation as a start.

**Comment by wesleytodd** [comment]
@hudovisk I made some comments which were never resolved.  If we can get them resolved I can include this in the next release.  Let me know if this is something you are still interested in working on.

**Comment by nicam** [comment]
Any chance to get this in?

**Pull request closed without merging**
